# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/oukihisashi/CLionProjects/CLoTH-Gossip

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/oukihisashi/CLionProjects/CLoTH-Gossip

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/oukihisashi/CLionProjects/CLoTH-Gossip/CMakeFiles /Users/oukihisashi/CLionProjects/CLoTH-Gossip//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/oukihisashi/CLionProjects/CLoTH-Gossip/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CLoTH_Gossip

# Build rule for target.
CLoTH_Gossip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLoTH_Gossip
.PHONY : CLoTH_Gossip

# fast build rule for target.
CLoTH_Gossip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/build
.PHONY : CLoTH_Gossip/fast

src/core/cloth.o: src/core/cloth.c.o
.PHONY : src/core/cloth.o

# target to build an object file
src/core/cloth.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/cloth.c.o
.PHONY : src/core/cloth.c.o

src/core/cloth.i: src/core/cloth.c.i
.PHONY : src/core/cloth.i

# target to preprocess a source file
src/core/cloth.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/cloth.c.i
.PHONY : src/core/cloth.c.i

src/core/cloth.s: src/core/cloth.c.s
.PHONY : src/core/cloth.s

# target to generate assembly for a file
src/core/cloth.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/cloth.c.s
.PHONY : src/core/cloth.c.s

src/core/event.o: src/core/event.c.o
.PHONY : src/core/event.o

# target to build an object file
src/core/event.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/event.c.o
.PHONY : src/core/event.c.o

src/core/event.i: src/core/event.c.i
.PHONY : src/core/event.i

# target to preprocess a source file
src/core/event.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/event.c.i
.PHONY : src/core/event.c.i

src/core/event.s: src/core/event.c.s
.PHONY : src/core/event.s

# target to generate assembly for a file
src/core/event.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/event.c.s
.PHONY : src/core/event.c.s

src/core/payments.o: src/core/payments.c.o
.PHONY : src/core/payments.o

# target to build an object file
src/core/payments.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/payments.c.o
.PHONY : src/core/payments.c.o

src/core/payments.i: src/core/payments.c.i
.PHONY : src/core/payments.i

# target to preprocess a source file
src/core/payments.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/payments.c.i
.PHONY : src/core/payments.c.i

src/core/payments.s: src/core/payments.c.s
.PHONY : src/core/payments.s

# target to generate assembly for a file
src/core/payments.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/core/payments.c.s
.PHONY : src/core/payments.c.s

src/data_structures/array.o: src/data_structures/array.c.o
.PHONY : src/data_structures/array.o

# target to build an object file
src/data_structures/array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/array.c.o
.PHONY : src/data_structures/array.c.o

src/data_structures/array.i: src/data_structures/array.c.i
.PHONY : src/data_structures/array.i

# target to preprocess a source file
src/data_structures/array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/array.c.i
.PHONY : src/data_structures/array.c.i

src/data_structures/array.s: src/data_structures/array.c.s
.PHONY : src/data_structures/array.s

# target to generate assembly for a file
src/data_structures/array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/array.c.s
.PHONY : src/data_structures/array.c.s

src/data_structures/heap.o: src/data_structures/heap.c.o
.PHONY : src/data_structures/heap.o

# target to build an object file
src/data_structures/heap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/heap.c.o
.PHONY : src/data_structures/heap.c.o

src/data_structures/heap.i: src/data_structures/heap.c.i
.PHONY : src/data_structures/heap.i

# target to preprocess a source file
src/data_structures/heap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/heap.c.i
.PHONY : src/data_structures/heap.c.i

src/data_structures/heap.s: src/data_structures/heap.c.s
.PHONY : src/data_structures/heap.s

# target to generate assembly for a file
src/data_structures/heap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/heap.c.s
.PHONY : src/data_structures/heap.c.s

src/data_structures/list.o: src/data_structures/list.c.o
.PHONY : src/data_structures/list.o

# target to build an object file
src/data_structures/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/list.c.o
.PHONY : src/data_structures/list.c.o

src/data_structures/list.i: src/data_structures/list.c.i
.PHONY : src/data_structures/list.i

# target to preprocess a source file
src/data_structures/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/list.c.i
.PHONY : src/data_structures/list.c.i

src/data_structures/list.s: src/data_structures/list.c.s
.PHONY : src/data_structures/list.s

# target to generate assembly for a file
src/data_structures/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/list.c.s
.PHONY : src/data_structures/list.c.s

src/data_structures/utils.o: src/data_structures/utils.c.o
.PHONY : src/data_structures/utils.o

# target to build an object file
src/data_structures/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/utils.c.o
.PHONY : src/data_structures/utils.c.o

src/data_structures/utils.i: src/data_structures/utils.c.i
.PHONY : src/data_structures/utils.i

# target to preprocess a source file
src/data_structures/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/utils.c.i
.PHONY : src/data_structures/utils.c.i

src/data_structures/utils.s: src/data_structures/utils.c.s
.PHONY : src/data_structures/utils.s

# target to generate assembly for a file
src/data_structures/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/data_structures/utils.c.s
.PHONY : src/data_structures/utils.c.s

src/network/network.o: src/network/network.c.o
.PHONY : src/network/network.o

# target to build an object file
src/network/network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/network/network.c.o
.PHONY : src/network/network.c.o

src/network/network.i: src/network/network.c.i
.PHONY : src/network/network.i

# target to preprocess a source file
src/network/network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/network/network.c.i
.PHONY : src/network/network.c.i

src/network/network.s: src/network/network.c.s
.PHONY : src/network/network.s

# target to generate assembly for a file
src/network/network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/network/network.c.s
.PHONY : src/network/network.c.s

src/network/routing.o: src/network/routing.c.o
.PHONY : src/network/routing.o

# target to build an object file
src/network/routing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/network/routing.c.o
.PHONY : src/network/routing.c.o

src/network/routing.i: src/network/routing.c.i
.PHONY : src/network/routing.i

# target to preprocess a source file
src/network/routing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/network/routing.c.i
.PHONY : src/network/routing.c.i

src/network/routing.s: src/network/routing.c.s
.PHONY : src/network/routing.s

# target to generate assembly for a file
src/network/routing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/network/routing.c.s
.PHONY : src/network/routing.c.s

src/simulation/htlc.o: src/simulation/htlc.c.o
.PHONY : src/simulation/htlc.o

# target to build an object file
src/simulation/htlc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/simulation/htlc.c.o
.PHONY : src/simulation/htlc.c.o

src/simulation/htlc.i: src/simulation/htlc.c.i
.PHONY : src/simulation/htlc.i

# target to preprocess a source file
src/simulation/htlc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/simulation/htlc.c.i
.PHONY : src/simulation/htlc.c.i

src/simulation/htlc.s: src/simulation/htlc.c.s
.PHONY : src/simulation/htlc.s

# target to generate assembly for a file
src/simulation/htlc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLoTH_Gossip.dir/build.make CMakeFiles/CLoTH_Gossip.dir/src/simulation/htlc.c.s
.PHONY : src/simulation/htlc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CLoTH_Gossip"
	@echo "... src/core/cloth.o"
	@echo "... src/core/cloth.i"
	@echo "... src/core/cloth.s"
	@echo "... src/core/event.o"
	@echo "... src/core/event.i"
	@echo "... src/core/event.s"
	@echo "... src/core/payments.o"
	@echo "... src/core/payments.i"
	@echo "... src/core/payments.s"
	@echo "... src/data_structures/array.o"
	@echo "... src/data_structures/array.i"
	@echo "... src/data_structures/array.s"
	@echo "... src/data_structures/heap.o"
	@echo "... src/data_structures/heap.i"
	@echo "... src/data_structures/heap.s"
	@echo "... src/data_structures/list.o"
	@echo "... src/data_structures/list.i"
	@echo "... src/data_structures/list.s"
	@echo "... src/data_structures/utils.o"
	@echo "... src/data_structures/utils.i"
	@echo "... src/data_structures/utils.s"
	@echo "... src/network/network.o"
	@echo "... src/network/network.i"
	@echo "... src/network/network.s"
	@echo "... src/network/routing.o"
	@echo "... src/network/routing.i"
	@echo "... src/network/routing.s"
	@echo "... src/simulation/htlc.o"
	@echo "... src/simulation/htlc.i"
	@echo "... src/simulation/htlc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

